myprog: sync.o backup.o myDaemon.o access.o 
	gcc -o myprog sync.o backup.o myDaemon.o access.o 
	
object: 
	gcc -c sync.c backup.c myDaemon.c access.c 
	
clean: 
	rm myprog sync.o backup.o myDaemon.o access.o 
